<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="9" passed="8" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-04-01T13:11:22 IST" name="Automation Suite" finished-at="2025-04-01T13:12:05 IST" duration-ms="42594">
    <groups>
    </groups>
    <test started-at="2025-04-01T13:11:22 IST" name="Zygal Connect Mobile App Test Cases" finished-at="2025-04-01T13:12:05 IST" duration-ms="42594">
      <class name="Test.loginPageTest">
        <test-method signature="loginWithValidCredentialsTest(org.testng.ITestContext)[pri:1, instance:Test.loginPageTest@3569fc08]" started-at="2025-04-01T13:11:22 IST" name="loginWithValidCredentialsTest" description="User Login with Valid Credentials" finished-at="2025-04-01T13:11:31 IST" duration-ms="9277" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@2c88b9fc]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithValidCredentialsTest -->
        <test-method signature="loginWithInvalidCredentialsTest(org.testng.ITestContext)[pri:2, instance:Test.loginPageTest@3569fc08]" started-at="2025-04-01T13:11:31 IST" name="loginWithInvalidCredentialsTest" finished-at="2025-04-01T13:11:33 IST" duration-ms="1141" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@2c88b9fc]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidCredentialsTest -->
        <test-method signature="loginWithInvalidEmail(org.testng.ITestContext)[pri:0, instance:Test.loginPageTest@3569fc08]" started-at="2025-04-01T13:11:33 IST" name="loginWithInvalidEmail" description="Verify Login with Invalid Email" finished-at="2025-04-01T13:11:36 IST" depends-on-methods="Test.loginPageTest.loginWithInvalidCredentialsTest" duration-ms="3725" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@2c88b9fc]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithInvalidEmail -->
        <test-method signature="loginWithNotRegisteredEmail(org.testng.ITestContext)[pri:0, instance:Test.loginPageTest@3569fc08]" started-at="2025-04-01T13:11:36 IST" name="loginWithNotRegisteredEmail" description="Verify Login with Not Registred Email" finished-at="2025-04-01T13:11:37 IST" depends-on-methods="Test.loginPageTest.loginWithInvalidEmail" duration-ms="379" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@2c88b9fc]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithNotRegisteredEmail -->
        <test-method signature="loginwithInvalidOTP(org.testng.ITestContext)[pri:0, instance:Test.loginPageTest@3569fc08]" started-at="2025-04-01T13:11:37 IST" name="loginwithInvalidOTP" description="Verify Login with Invalid OTP" finished-at="2025-04-01T13:11:39 IST" depends-on-methods="Test.loginPageTest.loginWithNotRegisteredEmail" duration-ms="2456" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@2c88b9fc]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginwithInvalidOTP -->
        <test-method signature="verifyAccountBlock(org.testng.ITestContext)[pri:0, instance:Test.loginPageTest@3569fc08]" started-at="2025-04-01T13:11:39 IST" name="verifyAccountBlock" description="Verify account block after attempting wrong OTP for 5 times" finished-at="2025-04-01T13:11:51 IST" depends-on-methods="Test.loginPageTest.loginwithInvalidOTP" duration-ms="12098" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@2c88b9fc]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAccountBlock -->
        <test-method signature="verifyGoToSignPage(org.testng.ITestContext)[pri:0, instance:Test.loginPageTest@3569fc08]" started-at="2025-04-01T13:11:51 IST" name="verifyGoToSignPage" description="Verify Go To Sign In page Navigation" finished-at="2025-04-01T13:11:53 IST" depends-on-methods="Test.loginPageTest.verifyAccountBlock" duration-ms="2180" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@2c88b9fc]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyGoToSignPage -->
        <test-method signature="verifyAccountBlockOnGetOtpPage(org.testng.ITestContext)[pri:0, instance:Test.loginPageTest@3569fc08]" started-at="2025-04-01T13:11:53 IST" name="verifyAccountBlockOnGetOtpPage" description="Verify that navigation and getOTP blocked for blocked account" finished-at="2025-04-01T13:11:54 IST" depends-on-methods="Test.loginPageTest.verifyGoToSignPage" duration-ms="717" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@2c88b9fc]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAccountBlockOnGetOtpPage -->
      </class> <!-- Test.loginPageTest -->
      <class name="Test.homePageTest">
        <test-method signature="verifyHomePageLoads(org.testng.ITestContext)[pri:0, instance:Test.homePageTest@35390ee3]" started-at="2025-04-01T13:11:54 IST" name="verifyHomePageLoads" description="Verify Home Page Loads Successfully" finished-at="2025-04-01T13:12:05 IST" depends-on-methods="Test.loginPageTest.loginWithValidCredentialsTest" duration-ms="10521" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@2c88b9fc]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Home Page did not load successfully. expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Home Page did not load successfully. expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at Test.homePageTest.verifyHomePageLoads(homePageTest.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyHomePageLoads -->
      </class> <!-- Test.homePageTest -->
    </test> <!-- Zygal Connect Mobile App Test Cases -->
  </suite> <!-- Automation Suite -->
</testng-results>
