<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-NB4I6K9" failures="1" tests="13" name="Test.loginPageTest" time="94.797" errors="0" timestamp="2025-05-19T17:20:38 IST" skipped="1">
  <testcase classname="Test.loginPageTest" name="verifyResendOTP" time="64.247">
    <failure message="Resend OTP failed: " type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Resend OTP failed: 
at org.testng.Assert.fail(Assert.java:111)
at Test.loginPageTest.verifyResendOTP(loginPageTest.java:259)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyResendOTP -->
  <testcase classname="Test.loginPageTest" name="verifyAdminViewerLoginBlock" time="0.733"/>
  <testcase classname="Test.loginPageTest" name="loginwithWrongOTP" time="2.464"/>
  <testcase classname="Test.loginPageTest" name="verifyAccountBlockOnGetOtpPage" time="0.771"/>
  <testcase classname="Test.loginPageTest" name="loginWithInvalidEmail" time="0.996"/>
  <testcase classname="Test.loginPageTest" name="verifySameEmailOnOtpPage" time="0.055"/>
  <testcase classname="Test.loginPageTest" name="verifyAccountBlockOnResendOtp" time="0.000">
    <skipped/>
  </testcase> <!-- verifyAccountBlockOnResendOtp -->
  <testcase classname="Test.loginPageTest" name="verifyEmptyUserEmail" time="1.419"/>
  <testcase classname="Test.loginPageTest" name="loginWithNotRegisteredEmail" time="0.727"/>
  <testcase classname="Test.loginPageTest" name="verifyAccountBlock" time="12.170"/>
  <testcase classname="Test.loginPageTest" name="verifyGoToSignPage" time="2.217"/>
  <testcase classname="Test.loginPageTest" name="loginWithValidCredentialsTest" time="7.464"/>
  <testcase classname="Test.loginPageTest" name="loginWithInvalidCredentialsTest" time="1.534"/>
</testsuite> <!-- Test.loginPageTest -->
